version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    container_name: riskos-backend
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    volumes:
      - ./backend:/app/backend
      - /app/backend/node_modules
    depends_on:
      - mongodb
    networks:
      - riskos-network

  flask-api:
    build:
      context: .
      dockerfile: flask.Dockerfile
    container_name: riskos-flask
    ports:
      - "5001:5001"
    volumes:
      - ./backend/flask-api:/app/flask-api
    networks:
      - riskos-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    container_name: riskos-frontend
    ports:
      - "80:80"
    depends_on:
      - backend
      - flask-api
    networks:
      - riskos-network

  mongodb:
    image: mongo:latest
    container_name: riskos-mongodb
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    networks:
      - riskos-network

networks:
  riskos-network:
    driver: bridge

volumes:
  mongodb_data: