version: '3.9'

services:
  flask:
    build:
      context: ./flask-api
    container_name: flask-container
    ports:
      - "5002:5002"
    restart: unless-stopped

  frontend:
    build:
      context: ./frontend
    container_name: frontend-container
    ports:
      - "5001:80"
    depends_on:
      - flask
    restart: unless-stopped

  backend:
    build:
      context: ./backend
    container_name: backend-container
    ports:
      - "5000:5000"
    env_file:
      - ./backend/.env
    depends_on:
      - frontend
      - flask
    restart: unless-stopped