services:
  backend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-backend:latest
    ports:
      - "5002:5000"  # Changed ports to avoid conflict
      - "5003:5001"
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    networks:
      - riskos-network

  frontend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-frontend:latest
    ports:
      - "80:80"
    depends_on:
      - backend
    networks:
      - riskos-network

networks:
  riskos-network:
    driver: bridge