version: '3'

services:
  backend:
    build:
      context: .
      dockerfile: backend.Dockerfile
    ports:
      - "5000:5000"  # Node.js API
      - "5001:5001"  # Flask API
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    volumes:
      - ./backend:/app
    restart: unless-stopped
    networks:
      - riskos-network

  frontend:
    build:
      context: .
      dockerfile: frontend.Dockerfile
    ports:
      - "80:80"
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - riskos-network

networks:
  riskos-network:
    driver: bridge