services:
  backend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-backend:${IMAGE_TAG:-latest}
    ports:
      - "5100:5000"  # Changed from 5002 → 5100 (avoids conflicts)
      - "5101:5001"  # Changed from 5003 → 5101
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_URI}
    restart: unless-stopped
    networks:
      - riskos-network

  frontend:
    image: ${DOCKER_REGISTRY}/${APP_NAME}-frontend:${IMAGE_TAG:-latest}
    ports:
      - "3000:80"  # Changed from 80 → 3000 (avoids root privileges + Jenkins conflict)
    depends_on:
      - backend
    restart: unless-stopped
    networks:
      - riskos-network

networks:
  riskos-network:
    driver: bridge